seed: 0
batch_size: 500
num_train_points: 500
num_test_points: 500 
dim: 1
dataset_name: student_teacher
data_filepath: "../datasets/student_teacher_1d_depth_5.csv"
noise: null 
n_qubits: 1
depth: 20
inputs: ["x"]
epochs: 1000 
optimizer: Adam 
lr: 0.01 
ansatz_gates: [RY]
fm_gates: [RX]
log_interval: 5
base_dir: "../results/1d/depth_5/fixed" 
grow: null