seed: 0
batch_size: 500
num_train_points: 1000
num_test_points: 1000
dim: 2 
dataset_name: student_teacher
data_filepath: "../datasets/sum_of_sines_2d_depth_5.csv"
noise: null 
n_qubits: 2
depth: 5 
inputs: ["x", "y"]
epochs: 1000 
optimizer: Adam
lr: 0.1
ansatz_gates: [RY]
fm_gates: [RX]
save_dir: "../results/2d/sines_5/block_growth" 
grow: 
  grow_type: "block"
  rate: 200
  step: 2 
  final_depth: 5 
  depth: 1