seed: 0
batch_size: 500
num_train_points: 500
num_test_points: 500
dim: 2 
dataset_name: student_teacher
data_filepath: "../datasets/student_teacher_2d_depth_5_hard.csv"
noise: null 
n_qubits: 2
depth: 5 
inputs: ["x", "y"]
epochs: 1000 
optimizer: Adam
lr: 0.01
ansatz_gates: [RY]
fm_gates: [RX]
log_interval: 5
base_dir: "../results/2d/depth_5/block_growth_adam" 
grow: 
  grow_type: "block"
  rate: 200
  step: 2 
  final_depth: 5 
  depth: 1